spring:

  datasource:
    url: jdbc:mysql://localhost:3306/AdapterTest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: JPAdapterDemo
  mvc:
    view:
      prefix: /
      suffix: .html
debug: true
server:
  port: 8080
